version: '3'

services:
  mysql:
    image: mysql:5.7.25
    container_name: dataflow-mysql
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.8.3-alpine
    container_name: dataflow-rabbitmq
    ports:
      - "5672:5672"
